//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juvoService
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class DangerEvents
    {
        public int ID { get; set; }
        public int DeviceId { get; set; }
        public string HappenedAt { get; set; }

        [JsonIgnore]
        public virtual Devices Devices { get; set; }
    }
}
