// <auto-generated />
namespace juvoService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kresic_ivan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kresic_ivan));
        
        string IMigrationMetadata.Id
        {
            get { return "201604160022039_kresic_ivan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
